### PR TITLE
Changing primary keys and adding data type on bankstatements

### PR DESCRIPTION
**Pull request by DylanBaker**
@drewbanin

### CODE REVIEW

**Comment by cmerrick** [comment]
Hi @DylanBaker, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

**Comment by cmerrick** [comment]
You did it @DylanBaker!

Thank you for signing the Singer Contribution License Agreement.

**Comment by KAllan357** [comment]
This looks good. I'm going to merge this and release it as 0.3.0 (even though its backwards incompatible with the PK change)

**Comment by KAllan357** [comment]
Actually, @DylanBaker do you want the values for `balance` and `available_balance` to be numbers before they are strings? The ordering matters when given an array of types.

**Comment by DylanBaker** [comment]
Ah. Yes, I do. I'll make that change.

**Comment by drewbanin** [comment]
@KAllan357 the jsonschema change here was necessitated by the following error in the Stitch replication logs:

```
Error persisting data for table "bank_statements": Record 17 did not conform to schema:
#: #: no subschema matched out of the total 1 subschemas
#: 4 schema violations found
#/balance: #: no subschema matched out of the total 2 subschemas
#/balance: expected: null, found: Double
#/balance: expected type: String, found: Double
#/availableBalance: #: no subschema matched out of the total 2 subschemas
#/availableBalance: expected: null, found: Double
#/availableBalance: expected type: String, found: Double
```

It's surprising to me that a double could not be coerced into a string. My suggestion was to add `number` to the list of types, but I'm curious if you think there's something else going on here

**Comment by KAllan357** [comment]
@drewbanin I see. I just looked at the source again - I see that this code is using its own transformation logic, not singer-python's.

Without any transformation via a library like singer-python, the data from the GET request will be unaltered and left as is. So what's likely happening is that the JSON response is returning a JSON number (ie `{ "balance": 3.14}`) which is failing schema validation when it reaches Stitch's gate.

This code is actually fine - you should get the behavior you want.

**Comment by drewbanin** [comment]
Roger! Thanks for the info :)

**Comment by KAllan357** [comment]
Released as 0.3.0

**Pull request merged**
